workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.19.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build Ionic
        script: |
          cd frontend
          npm run build
      - name: Add Android platform
        script: |
          cd frontend
          npx cap sync android
      - name: Build Android APK
        script: |
          cd frontend/android
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - lambertborrego1998@gmail.com
        notify:
          success: true
          failure: true
